import MypageActivities from '@/components/mypage/activity/MypageActivities'
import MypageHeader from '@/components/mypage/MypageHeader'
import { useAuthentication } from '@/hooks/useAuthentication'
import { useMypage } from '@/hooks/useMypage'
import { Box } from '@chakra-ui/layout'
import Head from 'next/head'
import React, { useEffect } from 'react'

export default function Home() {
  const { signInWithGithub, user } = useAuthentication({
    shouldInitialize: true,
  })
  const { initialize } = useMypage()

  useEffect(() => {
    if (!user) {
      return
    }
    initialize()
  }, [user])

  return (
    <Box background="#F6F8FA" height="100vh">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MypageHeader />

      <Box as="main">
        <MypageActivities />
      </Box>

      <button type="button" onClick={signInWithGithub}>
        signin with github
      </button>
      {user?.id}

      <footer></footer>
    </Box>
  )
}
