import MypageActivities from '@/components/mypage/activity/MypageActivities'
import MypageHeader, {
  mypageHeaderHeight,
} from '@/components/mypage/MypageHeader'
import MypageRepositories from '@/components/mypage/MypageRepositories'
import { useAuthentication } from '@/hooks/useAuthentication'
import { useMypage } from '@/hooks/useMypage'
import { Box, Heading } from '@chakra-ui/layout'
import Head from 'next/head'
import React, { useEffect } from 'react'

export default function Home() {
  const { signInWithGithub, user } = useAuthentication({
    shouldInitialize: true,
  })
  const { initialize } = useMypage()

  useEffect(() => {
    if (!user) {
      return
    }
    initialize()
  }, [user])

  return (
    <Box background="#F6F8FA" height="100vh">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MypageHeader />

      <Box as="main" display="flex">
        <Box
          background="white"
          width="310px"
          height={`calc(100vh - ${mypageHeaderHeight})`}
          overflowY="scroll"
          p={8}
        >
          <MypageRepositories />
        </Box>
        <Box p={8}>
          <MypageActivities />
        </Box>
      </Box>

      <footer></footer>
    </Box>
  )
}
