import MypageHeader from '@/components/mypage/MypageHeader'
import { useAuthentication } from '@/hooks/useAuthentication'
import axios from 'axios'
import Head from 'next/head'
import { useEffect } from 'react'

export default function Home() {
  const { apiHeaders, signInWithGithub, user } = useAuthentication()

  useEffect(() => {
    if (!user) {
      return
    }

    // axios.get('/api/github/activities', apiHeaders)
  }, [user])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MypageHeader />

      <button type="button" onClick={signInWithGithub}>
        signin with github
      </button>
      {user?.id}

      <main></main>

      <footer></footer>
    </div>
  )
}
